export default function TermsPage() {  return (    <div className="max-w-4xl mx-auto p-6">      <h1 className="text-3xl font-bold mb-4">Terms and Conditions</h1>      <p className="mb-4">Last updated: May 30, 2025</p>
      <p className="mb-4">        These Terms and Conditions ("Terms") govern your use of the OsTech Institute website (the "Platform"). By accessing or using this Platform, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use the Platform.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">1. Eligibility</h2>      <p className="mb-4">        You must be at least 13 years old to use this Platform. If you are under 18, you must have parental or guardian consent.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">2. Use of Content</h2>      <p className="mb-4">        All content, including courses, videos, graphics, and materials, are the property of OsTech Institute. You may not copy, distribute, or use any content for commercial purposes without our written consent.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">3. Account Responsibility</h2>      <p className="mb-4">        You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">4. Payments</h2>      <p className="mb-4">        All fees for courses or services are clearly displayed. Payments are non-refundable unless otherwise stated.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">5. Termination</h2>      <p className="mb-4">        We may terminate or suspend your account at any time if we believe you have violated these Terms.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">6. Limitation of Liability</h2>      <p className="mb-4">        OsTech Institute is not liable for any direct, indirect, incidental, or consequential damages resulting from your use of the Platform.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">7. Governing Law</h2>      <p className="mb-4">        These Terms shall be governed by and interpreted in accordance with the laws of the Federal Republic of Nigeria.      </p>
      <p className="mt-6">If you have questions about these Terms, please contact us at <a className="underline" href="mailto:support@ostech.institute">support@ostech.institute</a>.</p>    </div>  );}
