export default function PrivacyPage() {  return (    <div className="max-w-4xl mx-auto p-6">      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>      <p className="mb-4">Last updated: May 30, 2025</p>
      <p className="mb-4">        OsTech Institute respects your privacy. This Privacy Policy describes how we collect, use, and protect your information when you use our website or services.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">1. Information We Collect</h2>      <ul className="list-disc pl-6 mb-4">        <li>Personal information (name, email, phone number, etc.)</li>        <li>Account credentials and course progress</li>        <li>Payment information (processed securely via third-party providers)</li>        <li>Usage data (browser type, pages visited, IP address, etc.)</li>      </ul>
      <h2 className="text-xl font-semibold mt-6 mb-2">2. How We Use Your Information</h2>      <ul className="list-disc pl-6 mb-4">        <li>To provide access to courses and features</li>        <li>To process transactions</li>        <li>To improve our services and user experience</li>        <li>To send important notifications and updates</li>        <li>To comply with legal obligations</li>      </ul>
      <h2 className="text-xl font-semibold mt-6 mb-2">3. Data Security</h2>      <p className="mb-4">        We use industry-standard security measures to protect your data. However, no system is 100% secure, and we cannot guarantee absolute security.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">4. Sharing of Information</h2>      <p className="mb-4">        We do not sell your personal data. We may share information with trusted service providers for payment processing, analytics, or communication—only as necessary.      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">5. Your Rights</h2>      <p className="mb-4">        You have the right to access, update, or delete your personal information by contacting us. Nigerian users are protected under the Nigeria Data Protection Act (NDPA).      </p>
      <h2 className="text-xl font-semibold mt-6 mb-2">6. Changes to This Policy</h2>      <p className="mb-4">        We may update this policy from time to time. We encourage users to review it periodically.      </p>
      <p className="mt-6">If you have any questions or concerns, contact us at <a className="underline" href="mailto:support@ostech.institute">support@ostech.institute</a>.</p>    </div>  );}
